export const aboutCopy = {
  whoTab: "WHO I AM",
  doTab: "WHAT I DO",
  workTab: "WORK EXPERIENCE",
  name: "ANGKITHA ANGURAJ KUMAR",
  whoAmI: "WHO AM I",
  endOfPage: "END OF PAGE",
  arrow: "←",
  landing: "LANDING",
  projects: "PROJECTS",
  credit: "MADE BY ANGKITHA, SEP 2026",
  hobbiesTitle: "MY HOBBIES +  INTERESTS",
  spinMe: "SPIN ME!",
  stickyPlaceholder: "text here",
  hobbies: [
    { text: "Coffee, Food, & Cooking" },
    { text: "Film & TV" },
    { text: "Streetwear / Fashion" },
    { text: "Vinyl collection" },
    {
      text: "Music",
      children: ["Hip-Hop", "House", "Art Pop"],
    },
    {
      text: "Video Games",
      children: ["Zelda", "Resident Evil", "Final Fantasy"],
    },
    {
      text: "Travel! Some places I’ve been...",
      children: ["London", "Tokyo", "Rio", "Singapore", "Tamil Nadu"],
    },
    { text: "Photography" },
    {
      text: "Hybrid Training",
      children: ["Training for a full marathon!"],
    },
  ],
  workTitle: "MY ACADEMIC AND \nPROFESSIONAL EXPERIENCES",
  workSkills: [
    "FIGMA",
    "FIGJAM",
    "ADOBE PHOTOSHOP",
    "DESIGN SYSTEM FLUENCY",
    "UX RESEARCH",
    "VISUAL DESIGN",
    "INTERACTION DESIGN",
    "WCAG ACCESSIBILITY",
    "HEURISTIC ANALYSIS",
    "WIREFRAMING",
    "PROTOTYPING",
    "DATA VISUALIZATION",
    "CLAUDE",
    "CURSOR",
    "CODEX",
    "REACT",
    "TYPESCRIPT",
    "HTML/CSS",
    "DESIGN-TO-CODE HANDOFF",
    "FIGMA CODE CONNECT",
    "FIGMA SITES",
    "FRAMER",
    "REST APIS",
    "DTOS",
    "GIT",
    "CI/CD",
    "UNIT TESTING",
    "INTEGRATION TESTING",
    "STORYBOOK",
    "PLAYWRIGHT",
    "A/B TESTING",
    "USABILITY TESTING",
    "JIRA",
    "AGILE",
    "USER STORIES",
    "JOURNEY MAPPING",
    "0-TO-1 PRODUCT DESIGN",
    "CLIENT CO-DESIGN",
    "GOOGLE FOUNDATIONS OF UI",
    "CLAUDE CODE FOR VIBE CODING",
    "DATA ANALYTICS BY MICROSOFT",
  ],
  workExperience: [
    {
      role: "Design Engineer | Altimetrik",
      dates: "2025 - Present",
      items: [
        "Owned end-to-end UI/UX design for a financial enterprise platform modernization, introducing AI-enabled workflows that reduced client-facing calls from 12 to 4 minutes and task completion time by 83% ",
        "Engaged closely with 10 client-side employees via user interviews, A/B testing, and daily co-design sessions to rapidly incorporate real-time feedback to deliver product ready interfaces in 3 day design cycles",
        "Architected and documented scalable design systems across 3 projects, standardizing reusable components, tokens, and variables to streamline design-to-code handoff and reduce implementation ambiguity",
      ],
    },
    {
      role: "Software Engineer | L3Harris",
      dates: "2024 - 2025",
      items: [
        "Engineered Python-based automation for 50+ software validation tests, accelerating project delivery by 1 month and improving downstream engineering efficiency by 20%",
        "Mastered understanding of digital communication, using knowledge to develop 2 FPGAs for internal purposes",
        "Promoted to Trade Compliance team to establish LLM-powered internal workflow tools",
      ],
    },
    {
      role: "Software Engineering Intern | L3Harris",
      dates: "2023",
      items: [
        "Engineered an audio codec FPGA from scratch using MATLAB and Verilog, reducing 15 hours from assigned project timeline",
        "Formulated a Python script to map internal employee statistics to accessible dashboards, enhancing data accessibility for business analysts and reducing assignment downtime from 3 to 1 day",
      ],
    },
    {
      role: "VP Finance, Alpha Phi Omega Rho Pi",
      dates: "2024",
      items: [
        "Tracked chapter budget for 50+ active members and 30 prospective members",
        "Advised expenditures for 15 integral chapter events, actively saving ~95% of chapter funds",
        "Planned and coordinated 2 fundraising events, bringing in $400+ in funds to the chapter",
      ],
    },
    {
      role: "Treasurer, Society of Women Engineers @ UC San Diego",
      dates: "2021-2023",
      items: [
        "Raised and managed $45,000 for the organization by engaging corporate sponsors",
        "Advocated for student and sponsor interests by organizing orders for 30+ events held by SWE from 2021-2023",
        "Achieved a 20% surplus from projected budget and boosted participation by 40% through incentives and firm budgeting",
      ],
    },
  ],
  hello: "hey this is angkitha!",
  note1:
    "thank you for navigating my page. i’m a product designer with proven design and front-end know-how and a penchant for refined and organized web-based solutions.",
  note2:
    "it would mean the world to me if you could take some time to explore all this site has to offer... so I don’t seem some 1D individual that only chants about work. i do a lot more!",
  note3:
    "as always, please feel free to reach out to me via my linkedin to connect. i love talking to people, even if it’s not about work! :D",
};
